package com.manef.ecommerce.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

/**
 * Our standard internal delivery response.
 * This is OUR format — translated FROM
 * whatever format the delivery company returned.
 *
 * OrderService only sees this standard format
 * regardless of which company processed the shipment.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DeliveryResponse {

    /**
     * Whether the shipment was created successfully.
     * true  → tracking number and fee are valid
     * false → something went wrong, check errorMessage
     */
    private boolean success;

    /**
     * The tracking number generated by the delivery company.
     * Shown to the customer on the thank you page.
     * e.g. "TRK-123456789"
     */
    private String trackingNumber;

    /**
     * Shipping fee calculated by the delivery company.
     * Based on weight, distance, and service type.
     * Added to the order's shippingFee field.
     */
    private BigDecimal shippingFee;

    /**
     * Estimated delivery date as a string.
     * e.g. "2-3 business days"
     * Shown to the customer on the thank you page.
     */
    private String estimatedDelivery;

    /**
     * Raw JSON response from the delivery company.
     * Stored in the order's deliveryApiResponse field
     * as a safety net — if we need to debug later.
     */
    private String rawResponse;

    /**
     * Error message if success = false.
     * Used for logging and admin notifications.
     */
    private String errorMessage;
}